
###
# Sample Vagrantfile for myslef
###

Vagrant.configure("2") do |config|
  config.vm.hostname = "backend01"
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", bridge: "wlxe4beedcb8f63"
  config.vm.provider "virtualbox" do |v|
      v.name = "backend01"
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
