apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  REACT_APP_PUBLIC_URL: {{ .Values.REACT_APP_PUBLIC_URL }}
  REACT_APP_API_URL: {{ .Values.REACT_APP_API_URL }}
  REACT_APP_API_AUTH_METHOD: {{ .Values.REACT_APP_API_AUTH_METHOD }}
  BROWSER: {{ .Values.BROWSER }}
  SKIP_PREFLIGHT_CHECK: {{ .Values.SKIP_PREFLIGHT_CHECK }}
